server:
  port: 8081  # Spring boot Server port

spring:
  batch:
    initializ

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2_db

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
messages:
  basename: i18n/exception
  encoding: UTF-8

jwt:
  secret: VmpKMGEyTXlTa2hWYTFwT1ZqSm9jRmxzVm1Ga1ZtUnpXVE5vYVZJd2NERldWM1JMWVd4T1JsSlVhejA9

file:
  upload:
    location: /Users/jojaeyeong/Desktop/diet/src/main/resources/static/